[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tomocpt"
version = "0.5.2"
description = "Python tools for picking cryo Tomograms"
readme = "README.md"
keywords = ["particle picking", "cryoEM", "tomograms"]
authors = [
    {name = "Pranav NM Shah", email = "p.shah.lab@gmail.com"},
    {name = "Ruben Sanchez-Garcia"}
]
license = {text = "AGPL-3.0"}
requires-python = ">=3.8"
dependencies = [
    "hydra-core==1.3.2",
    "imodmodel==0.0.13",
    "joblib==1.4.2",
    "kornia==0.7.4",
    "matplotlib==3.10.0",
    "monai==1.4.0",
    "mrcfile==1.5.3",
    "numpy==1.26.4",
    "omegaconf==2.3.0",
    "pandas==2.2.3",
    "psutil==6.1.0",
    "pytorch-lightning==2.4.0",
    "scikit-image==0.24.0",
    "scikit-learn==1.6.0",
    "scipy==1.14.1",
    "starfile==0.5.10",
    "tensorboard==2.18.0",
    "tifffile==2024.9.20",
    "torch==2.5.1",
    "torchio==0.20.2",
    "torchmetrics==1.6.0",
    "torchvision==0.20.1",
    "tqdm==4.67.1",
    "typer==0.13.1",
    "einops==0.8.0",
    "dask==2025.5.0",
    "dask-cuda==25.6.0",
    "click==8.1.7"
]

[project.urls]
Homepage = "https://github.com/shahpnmlab/tomocpt"

[project.scripts]
tomocpt = "tomocpt.main:main"

[tool.setuptools]
packages = ["tomocpt"]
include-package-data = true
