#### For auto configuration -> TODO: Easier config
PACKAGE_NAME = "PYCOTOOL"
USER_CONFIG_YAML_ENV_VARNAME = PACKAGE_NAME + "_CONFIGYML"
configParamName = "configFile"
modelParamName = "modelFname"

### FOR TRAINING
TRAIN_DIR_NAME = "train"
VAL_DIR_NAME = "val"
PYCO_MD_FILE_NAME = "pyco_md.csv"
VOLUMES_DIR_NAME_PREFIX = "volumes"
LABELS_DIR_NAME_PREFIX = "labels%s" #labels{selfSup|supervised}
PERCENT_TO_VALIDATE = 0.2
RAW_VOL_FNAME_PATTERN = r'([\w\-_]+)\.mrc'
RAW_LABEL_FNAME_TEMPLATE = "%s.labels.mrc"
CUBES_EXTENSION = ".nii.gz"
CUBES_FNAMES_TEMPLATES = "%s/%s_%d_%d_%d_%d" + CUBES_EXTENSION  #{VOLUMES_DIR_NAME_PREFIX/LABELS_DIR_NAME_PREFIX}/chunk_{ID}_[Z]_[Y]_[X]
# ------------------ADVANCED KNOBS --------------------------- #
CHUNK_SIZE = 64
CHUNK_STRIDE = 32
RANDOM_FRACTION_TO_SAMPLE_TRAIN = -1  # Train on all the chunks

#### THIS IS CONFIG FOR U-NET
FIRST_LAYER_OUT_CHANNELS = 32
NUM_LEVELS = 5
CHANNELS_INCREASE_FACTOR = 2
KERNEL_SIZE = 5
CONV_DILATION = 1
LEARNING_RATE = 4e-4
FACTOR_REDUCE_LR_PLATEAU_N_EPOCHS = 0.5
COSINE_LR_SCHEDULE_N_EPOCHS = 6
PATIENT_REDUCE_LR_PLATEAU_N_EPOCHS = 6

##### THIS IS CONFIG FOR SWINUNETR
SWINUNETR_FEAT_SIZE = 12*3  # Should be multiple of 12

# THIS IS FOR PRETRAIN
NOISE2NOISE_RAND_MASK_SIZE = 15
CONTRAST_LOSS_L1_EMB_REGULARIZATION = 1e-4
CONTRAST_LOSS_TEMPERATURE = 1e-1

#BCE Loss val
BCE_EPS = 1

#FASTER TRAINING ARGS
LIMIT_VALIDATION_BATCHES = 1
VAL_CHECK_INTERVAL = 1

TORCH_MATMUL_PRECISION = "medium" # "medium" "high" "highest"
TORCH_FLOAT_PRECISION = '32' # '32' # '16' 'bf16'

SEED_FOR_TRAIN_VAL_SPLIT = 113
