
# ------------------ADVANCED KNOBS --------------------------- #
CHUNK_SIZE = 64
CHUNK_STRIDE = 32
RANDOM_FRACTION_TO_SAMPLE_TRAIN = -1  # Train on all the chunks

MODEL_TYPE = "swinunetr" # or unet
#### THIS IS CONFIG FOR U-NET
IN_CHANNELS = 1
FIRST_LAYER_OUT_CHANNELS = 32
NUM_LEVELS = 5
CHANNELS_INCREASE_FACTOR = 2
KERNEL_SIZE = 5
CONV_DILATION = 1
LAST_ACTIVATION_LAYER = "linear" #or "sigmoid"
STRIDE_CONV_INSTEAD_OF_POOLING = False
OUTPUT_DIM = "same"
LEARNING_RATE = 4e-4
FACTOR_REDUCE_LR_PLATEAU_N_EPOCHS = 0.5
COSINE_LR_SCHEDULE_N_EPOCHS = 6
PATIENT_REDUCE_LR_PLATEAU_N_EPOCHS = 6

##### THIS IS CONFIG FOR SWINUNETR
SWINUNETR_FEAT_SIZE = 12*3  # Should be multiple of 12
DROP_RATE = 0.3
ATTN_DROP_RATE = 0.3
DROPOUT_PATH_RATE = 0.2

# THIS IS FOR PRETRAIN
NOISE2NOISE_RAND_MASK_SIZE = 15
CONTRAST_LOSS_L1_EMB_REGULARIZATION = 1e-4
CONTRAST_LOSS_TEMPERATURE = 1e-1

#BCE Loss val
BCE_EPS = 1

#FASTER TRAINING ARGS
LIMIT_VALIDATION_BATCHES = 1
VAL_CHECK_INTERVAL = 1

TORCH_MATMUL_PRECISION = "medium" # "medium" "high" "highest"
TORCH_FLOAT_PRECISION = '32' # '32' # '16' 'bf16'

SEED_FOR_TRAIN_VAL_SPLIT = 113